(defun mean (l &optional (sum 0) (n 0))
   (if (endp l)
	(handler-case (/ sum n)
		(error (c)
		(format t "Caught exception")
		)
	)
       (mean (cdr l) 
            (+ sum (car l)) 
            (+ 1 n))
	)
)
