(defun partea-reala (c)
    (if (complexp c)
        (realpart c)
        (format t "Numarul nu este complex")
    )
)
(defun partea-imaginara (c)
    (if (complexp c)
        (imagpart c)
        (format t "Numarul nu este complex")
    )
)
(defun afisare-complex (c)
    (if (complexp c)
        (format t "~d = ~d + ~d*i" c (partea-reala c) (partea-imaginara c))
        (format t "Numarul nu este complex")
    )
)
(defun complex-egale (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (equalp c1 c2)
        (format t "Numerele nu sunt complexe")
    )
)
(defun adunare-complex (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (+ c1 c2)
        (format t "Numerele nu sunt complexe")
    )
)
(defun scadere-complex (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (- c1 c2)
        (format t "Numerele nu sunt complexe")
    )
)
(defun inmultire-complex (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (* c1 c2)
        (format t "Numerele nu sunt complexe")
    )
)
(defun impartire-complex (c1 c2)
    (if (and (complexp c1) (complexp c2))
        (/ c1 c2)
        (format t "Numerele nu sunt complexe")
    )
)